"use strict";
const PANELS=[
{id:"markets",label:"Markets",options:[["S&P 500","OANDA:SPX500USD"],["Nasdaq 100","OANDA:NAS100USD"],["Dow Jones","OANDA:US30USD"],["FTSE 100","OANDA:UK100GBP"],["DAX","OANDA:DE30EUR"],["Euro Stoxx 50","OANDA:EU50EUR"],["SMI (Swiss)","OANDA:CH20CHF"],["Nikkei 225","OANDA:JP225USD"],["Hang Seng","OANDA:HK33HKD"],["ASX 200","OANDA:AU200AUD"]]},
{id:"commodities",label:"Commodities",options:[["Brent","OANDA:BCOUSD"],["WTI","OANDA:WTICOUSD"],["Nat Gas","OANDA:NATGASUSD"],["Gold","OANDA:XAUUSD"],["Silver","OANDA:XAGUSD"],["Copper","OANDA:XCUUSD"],["Platinum","OANDA:XPTUSD"],["Palladium","OANDA:XPDUSD"],["Corn","OANDA:CORNUSD"],["Wheat","OANDA:WHEATUSD"]]},
{id:"fx",label:"FX",options:[["EUR/CHF","OANDA:EURCHF"],["USD/CHF","OANDA:USDCHF"],["GBP/CHF","OANDA:GBPCHF"],["EUR/USD","OANDA:EURUSD"],["GBP/USD","OANDA:GBPUSD"],["USD/JPY","OANDA:USDJPY"],["EUR/GBP","OANDA:EURGBP"],["USD/CNH","OANDA:USDCNH"],["AUD/USD","OANDA:AUDUSD"],["DXY","TVC:DXY"]]},
{id:"rates",label:"Rates / Bonds",options:[["TLT 20Y+","AMEX:TLT"],["IEF 7-10Y","AMEX:IEF"],["IEI 3-7Y","AMEX:IEI"],["SHY 1-3Y","AMEX:SHY"],["BIL T-Bills","AMEX:BIL"],["HYG","AMEX:HYG"],["LQD","AMEX:LQD"],["DXY","TVC:DXY"]]}
];
const HOT=[["Apple","NASDAQ:AAPL"],["Microsoft","NASDAQ:MSFT"],["Nvidia","NASDAQ:NVDA"],["Amazon","NASDAQ:AMZN"],["Meta","NASDAQ:META"],["Alphabet","NASDAQ:GOOGL"],["Tesla","NASDAQ:TSLA"],["Berkshire","NYSE:BRK.B"],["Nestle","SIX:NESN"],["Roche","SIX:ROG"],["Novartis","SIX:NOVN"],["UBS","SIX:UBSG"],["ASML","EURONEXT:ASML"],["LVMH","EURONEXT:MC"],["Toyota","TSE:7203"],["Orron Energy","OMXSTO:ORRON"]];
const LOCAL=HOT.concat([["JPM","NYSE:JPM"],["Visa","NYSE:V"],["Lilly","NYSE:LLY"],["Broadcom","NASDAQ:AVGO"],["Netflix","NASDAQ:NFLX"],["AMD","NASDAQ:AMD"],["Palantir","NYSE:PLTR"],["Exxon","NYSE:XOM"],["SAP","XETR:SAP"],["Richemont","SIX:CFR"],["ABB","SIX:ABBN"]]);
const KEY="markets-monitor:v5";
function defState(){return{page:"monitor",interval:"D",studies:"ma",layout:"grid",theme:"dark",phoneIndex:0,equity:{name:"Apple",symbol:"NASDAQ:AAPL"},selections:Object.fromEntries(PANELS.map(p=>[p.id,p.options[0][1]])),custom:Object.fromEntries(PANELS.map(p=>[p.id,[]]))};}
function load(){const c=defState();try{const s=JSON.parse(localStorage.getItem(KEY)||"null");if(!s)return c;if(s.page)c.page=s.page;if(s.interval)c.interval=s.interval;if(s.studies)c.studies=s.studies;if(s.layout)c.layout=s.layout;if(s.theme)c.theme=s.theme;if(s.equity&&s.equity.symbol)c.equity=s.equity;if(s.selections)Object.assign(c.selections,s.selections);if(s.custom)c.custom=s.custom;}catch(e){}return c;}
let state=load();let tvP=null;const dash=document.getElementById("dashboard");
const runtime=Object.fromEntries(PANELS.map(p=>[p.id,{v:0,vis:false,done:false}]));runtime.equity={v:0,vis:true,done:false};
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}}
function opts(id){return PANELS.find(p=>p.id===id).options.concat(state.custom[id]||[]);}
function nameOf(id){const m=opts(id).find(o=>o[1]===state.selections[id]);return m?m[0]:state.selections[id];}
function studies(){const a=[];if(state.studies.includes("ma"))a.push({id:"MASimple@tv-basicstudies",inputs:{length:50}},{id:"MASimple@tv-basicstudies",inputs:{length:100}},{id:"MASimple@tv-basicstudies",inputs:{length:200}});if(state.studies.includes("vol"))a.push({id:"Volume@tv-basicstudies"});if(state.studies.includes("rsi"))a.push({id:"RSI@tv-basicstudies",inputs:{length:14}});return a;}
function loadTV(){if(window.TradingView)return Promise.resolve(window.TradingView);if(tvP)return tvP;tvP=new Promise((res,rej)=>{const s=document.createElement("script");s.src="https://s3.tradingview.com/tv.js";s.async=true;s.onload=()=>window.TradingView?res(window.TradingView):rej(Error("no tv"));s.onerror=()=>rej(Error("tv blocked"));document.head.append(s);});return tvP;}
function status(id,mode,msg){const el=document.getElementById("status_"+id);if(!el)return;if(mode==="ready"){el.hidden=true;el.replaceChildren();return;}el.hidden=false;el.textContent=msg||"";}
async function render(id,force){const r=runtime[id];if(!r)return;if(!force&&!r.vis&&!r.done)return;r.done=true;r.v++;const box=document.getElementById("chart_"+id);if(!box)return;box.replaceChildren();const sym=id==="equity"?state.equity.symbol:state.selections[id];const nm=id==="equity"?state.equity.name:nameOf(id);status(id,"loading","Loading "+nm);try{const TV=await loadTV();box.replaceChildren();new TV.widget({autosize:true,symbol:sym,interval:state.interval,timezone:"Europe/Zurich",theme:state.theme,style:"1",locale:"en",hide_side_toolbar:true,allow_symbol_change:id==="equity",studies:studies(),container_id:"chart_"+id,support_host:"https://www.tradingview.com"});setTimeout(()=>status(id,"ready"),1600);}catch(e){status(id,"err",e.message);}}
function build(){const add=document.getElementById("addPanelSelect");add.replaceChildren();const f=document.createDocumentFragment();PANELS.forEach(cfg=>{add.add(new Option(cfg.label,cfg.id));const p=document.createElement("section");p.className="panel";p.id="panel_"+cfg.id;p.dataset.panelId=cfg.id;const sel=document.createElement("select");sel.className="instrument-select";sel.id="select_"+cfg.id;sel.dataset.panelId=cfg.id;opts(cfg.id).forEach(([n,s])=>sel.add(new Option(n,s,false,s===state.selections[cfg.id])));p.innerHTML='<div class="panel-head"><div><span class="panel-label"></span><strong class="panel-title" id="title_'+cfg.id+'"></strong><div class="panel-meta" id="meta_'+cfg.id+'"></div></div><div class="panel-controls"></div></div><div class="chart-stage"><div class="chart" id="chart_'+cfg.id+'"></div><div class="chart-status" id="status_'+cfg.id+'"></div></div>';p.querySelector(".panel-label").textContent=cfg.label;p.querySelector(".panel-title").textContent=nameOf(cfg.id);p.querySelector(".panel-meta").textContent=state.selections[cfg.id];p.querySelector(".panel-controls").append(sel);f.append(p);});dash.replaceChildren(f);}
function phone(){const on=matchMedia("(max-width:760px)").matches&&state.page==="monitor";document.body.classList.toggle("is-phone-focus",on);if(!on)return;state.phoneIndex=((state.phoneIndex%PANELS.length)+PANELS.length)%PANELS.length;PANELS.forEach((p,i)=>document.getElementById("panel_"+p.id).classList.toggle("is-phone-active",i===state.phoneIndex));document.getElementById("mobilePanelLabel").textContent=PANELS[state.phoneIndex].label;const id=PANELS[state.phoneIndex].id;runtime[id].vis=true;render(id,true);}
function setPage(pg){state.page=pg;save();document.getElementById("monitorPage").classList.toggle("is-on",pg==="monitor");document.getElementById("equitiesPage").classList.toggle("is-on",pg==="equities");document.getElementById("pageMonitor").classList.toggle("is-on",pg==="monitor");document.getElementById("pageEquities").classList.toggle("is-on",pg==="equities");phone();if(pg==="equities"){document.getElementById("equityTitle").textContent=state.equity.name;document.getElementById("equityMeta").textContent=state.equity.symbol;render("equity",true);}}
function apply(){document.getElementById("intervalSelect").value=state.interval;document.getElementById("studiesSelect").value=state.studies;dash.classList.toggle("is-stacked",state.layout==="stack");document.documentElement.dataset.theme=state.theme;document.getElementById("themeButton").textContent=state.theme==="dark"?"Light":"Dark";setPage(state.page);}
function lazy(){if(!("IntersectionObserver"in window)){PANELS.forEach(p=>{runtime[p.id].vis=true;render(p.id,true);});return;}const io=new IntersectionObserver(es=>es.forEach(e=>{const id=e.target.dataset.panelId;runtime[id].vis=e.isIntersecting;if(e.isIntersecting)render(id,false);}),{rootMargin:"240px"});PANELS.forEach(p=>io.observe(document.getElementById("panel_"+p.id)));}
function pick(item){state.equity={name:item.name,symbol:item.symbol};save();document.getElementById("equitySearch").value=item.symbol;document.getElementById("equitySuggest").hidden=true;document.getElementById("equityTitle").textContent=item.name;document.getElementById("equityMeta").textContent=item.symbol;[...document.querySelectorAll(".chip")].forEach(c=>c.classList.toggle("is-on",c.dataset.symbol===item.symbol));render("equity",true);}
function localQ(q){const n=q.trim().toLowerCase();const src=n?LOCAL.filter(([a,b])=>a.toLowerCase().includes(n)||b.toLowerCase().includes(n)):HOT;return src.slice(0,12).map(([name,symbol])=>({name,symbol,exchange:symbol.split(":")[0]}));}
async function remoteQ(q){const u="https://symbol-search.tradingview.com/symbol_search/v3/?text="+encodeURIComponent(q)+"&hl=1&lang=en&search_type=stock&domain=production";const r=await fetch(u);if(!r.ok)throw 0;const d=await r.json();const rows=Array.isArray(d)?d:(d.symbols||[]);return rows.slice(0,12).map(row=>{const t=row.symbol||row.ticker||"";const ex=row.exchange||row.prefix||"";const symbol=row.prefix&&row.symbol?row.prefix+":"+row.symbol:(ex&&t?ex+":"+t:t);return{name:(row.description||t).replace(/<\/?em>/g,""),symbol,exchange:ex};}).filter(x=>x.symbol);}
function drawSug(items){const box=document.getElementById("equitySuggest");box.replaceChildren();if(!items.length){box.hidden=true;return;}items.forEach(it=>{const b=document.createElement("button");b.type="button";b.innerHTML='<span class="sym"></span><span class="ex"></span><span class="desc"></span>';b.querySelector(".sym").textContent=it.symbol;b.querySelector(".ex").textContent=it.exchange||"";b.querySelector(".desc").textContent=it.name;b.onmousedown=e=>{e.preventDefault();pick(it);};box.append(b);});box.hidden=false;}
async function search(q){const loc=localQ(q);drawSug(loc);if(!q.trim())return;try{const rem=await remoteQ(q.trim());if(rem.length)drawSug(rem);}catch(e){}}
function chips(){const box=document.getElementById("equityChips");box.replaceChildren();HOT.forEach(([name,symbol])=>{const b=document.createElement("button");b.type="button";b.className="chip"+(symbol===state.equity.symbol?" is-on":"");b.dataset.symbol=symbol;b.textContent=name;b.onclick=()=>pick({name,symbol});box.append(b);});}
function clocks(){const g=document.getElementById("genevaClock"),u=document.getElementById("utcClock");const gf=new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Zurich",weekday:"short",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false});const uf=new Intl.DateTimeFormat("en-GB",{timeZone:"UTC",weekday:"short",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false});const t=()=>{const n=new Date();g.textContent=gf.format(n);u.textContent=uf.format(n);};t();setInterval(t,1000);}
dash.addEventListener("change",e=>{const s=e.target.closest("select[data-panel-id]");if(!s)return;state.selections[s.dataset.panelId]=s.value;document.getElementById("title_"+s.dataset.panelId).textContent=nameOf(s.dataset.panelId);save();render(s.dataset.panelId,true);});
document.getElementById("intervalSelect").onchange=()=>{state.interval=intervalSelect.value;save();[...PANELS.map(p=>p.id),"equity"].forEach(id=>runtime[id].done&&render(id,true));};
document.getElementById("studiesSelect").onchange=()=>{state.studies=studiesSelect.value;save();[...PANELS.map(p=>p.id),"equity"].forEach(id=>runtime[id].done&&render(id,true));};
document.getElementById("layoutButton").onclick=()=>{state.layout=state.layout==="grid"?"stack":"grid";save();apply();};
document.getElementById("themeButton").onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";save();apply();[...PANELS.map(p=>p.id),"equity"].forEach(id=>runtime[id].done&&render(id,true));};
document.getElementById("refreshButton").onclick=()=>state.page==="equities"?render("equity",true):PANELS.forEach(p=>render(p.id,true));
document.getElementById("resetButton").onclick=()=>{state=defState();save();apply();PANELS.forEach(p=>render(p.id,true));};
document.getElementById("addSymbolButton").onclick=()=>document.getElementById("addBar").classList.toggle("is-open");
document.getElementById("addConfirmButton").onclick=()=>{const id=addPanelSelect.value,n=addNameInput.value.trim(),s=addSymbolInput.value.trim().toUpperCase();if(!n||!s)return;state.custom[id]=state.custom[id].filter(x=>x[1]!==s);state.custom[id].push([n,s]);state.selections[id]=s;save();build();render(id,true);};
document.getElementById("prevPanelButton").onclick=()=>{state.phoneIndex--;save();phone();};
document.getElementById("nextPanelButton").onclick=()=>{state.phoneIndex++;save();phone();};
document.getElementById("pageMonitor").onclick=()=>setPage("monitor");
document.getElementById("pageEquities").onclick=()=>setPage("equities");
const q=document.getElementById("equitySearch");let st;
q.addEventListener("input",()=>{clearTimeout(st);st=setTimeout(()=>search(q.value),160);});
q.addEventListener("focus",()=>search(q.value));
q.addEventListener("blur",()=>setTimeout(()=>{equitySuggest.hidden=true;},180));
window.addEventListener("resize",phone);
build();chips();apply();clocks();lazy();
