"""Instrument universe for the Table page.

Each row: (yahoo_symbol, display_name, tradingview_symbol or None, kind, note)
kind: equity | etf | future | index | fx | yield
Rationale strings for the 'Strategic peers' sub-group are a speculative, illustrative screen of listed
strategic / financial investors active in European renewables. They are not based on any reported approach.
"""

def R(sym, name, tv=None, kind="equity", note=None):
    return dict(sym=sym, name=name, tv=tv, kind=kind, note=note)

GROUPS = [
    dict(id="nordic", label="Nordic Renewables", sections=[
        dict(label=None, rows=[
            R("CLOUD.OL", "Cloudberry Clean Energy", "OSL:CLOUD"),
            R("SCATC.OL", "Scatec", "OSL:SCATC"),
            R("EOLU-B.ST", "Eolus B", "OMXSTO:EOLU_B"),
            R("ORRON.ST", "Orrön Energy", "OMXSTO:ORRON"),
            R("MGN.OL", "Magnora", "OSL:MGN"),
            R("ORSTED.CO", "Ørsted", "OMXCOP:ORSTED"),
            R("VWS.CO", "Vestas Wind Systems", "OMXCOP:VWS"),
            R("FORTUM.HE", "Fortum", "OMXHEX:FORTUM"),
            R("RWE.DE", "RWE", "XETR:RWE"),
            R("EDPR.LS", "EDP Renováveis", "EURONEXT:EDPR"),
            R("ANE.MC", "Acciona Energía", "BME:ANE"),
            R("SLR.MC", "Solaria", "BME:SLR"),
            R("GRE.MC", "Grenergy", "BME:GRE"),
            R("ERG.MI", "ERG", "MIL:ERG"),
            R("VLTSA.PA", "Voltalia", "EURONEXT:VLTSA"),
            R("NDX1.DE", "Nordex", "XETR:NDX1"),
        ]),
        dict(label="Benchmarks",
             note="Listed clean-energy / renewables UCITS ETFs for context (price returns, local currency).",
             rows=[
            R("INRG.L", "iShares Global Clean Energy (UCITS)", "LSE:INRG", "etf"),
            R("R4RU.DE", "Global X Renewable Energy Producers (UCITS)", "XETR:R4RU", "etf"),
            R("RENW.L", "L&G Clean Energy (UCITS)", "LSE:RENW", "etf"),
            R("WNDY.L", "Global X Wind Energy (UCITS)", "LSE:WNDY", "etf"),
        ]),
        dict(label="Strategic peers",
             note="Speculative, illustrative screen of listed strategic and financial investors active in "
                  "European renewables. Not based on any reported approach; not investment advice. "
                  "Hover a name for the rationale.",
             rows=[
            R("FORTUM.HE", "Fortum", "OMXHEX:FORTUM", note="Nordic hydro/nuclear utility (Finnish state ~51%); strategy targets growth in Nordic onshore wind/solar, strong balance sheet."),
            R("EQNR.OL", "Equinor", "OSL:EQNR", note="Norwegian state-controlled major with a power/renewables arm; has bought onshore platforms before (BeGreen, Wento) and holds ~10% of Ørsted."),
            R("AKER.OL", "Aker ASA", "OSL:AKER", note="Oslo-based industrial holding with a renewables history (Aker Horizons / Mainstream); natural home-market consolidator."),
            R("BONHR.OL", "Bonheur", "OSL:BONHR", note="Parent of Fred. Olsen Renewables, operating onshore wind in Norway, Sweden and the UK; direct Nordic onshore fit."),
            R("VER.VI", "Verbund", "VIE:VER", note="Hydro-heavy Austrian utility (state ~51%) expanding renewables abroad; Nordic hydro/wind would diversify its base."),
            R("TTE.PA", "TotalEnergies", "EURONEXT:TTE", note="Integrated Power growth ambition; has bought renewables developers/platforms (e.g. Total Eren, VSB)."),
            R("RWE.DE", "RWE", "XETR:RWE", note="Large-scale European renewables/generation player; Nordic onshore would be a bolt-on (lower priority vs offshore/US)."),
            R("BEP", "Brookfield Renewable", "NYSE:BEP", note="Serial acquirer of listed renewables platforms, incl. European take-privates (e.g. Neoen with Temasek)."),
            R("EQT.ST", "EQT AB", "OMXSTO:EQT", note="Nordic private-markets manager whose infrastructure funds took Swedish developer OX2 private (2024)."),
            R("KKR", "KKR", "NYSE:KKR", note="Infrastructure funds active in European renewables take-privates (Encavis, Greenvolt in 2024)."),
        ]),
    ]),
    dict(id="energy", label="Energy", sections=[dict(label=None, rows=[
        R("SHEL.L", "Shell", "LSE:SHEL"),
        R("BP.L", "BP", "LSE:BP"),
        R("TTE.PA", "TotalEnergies", "EURONEXT:TTE"),
        R("XOM", "Exxon Mobil", "NYSE:XOM"),
        R("EQNR.OL", "Equinor", "OSL:EQNR"),
        R("COP", "ConocoPhillips", "NYSE:COP"),
        R("CNQ.TO", "Canadian Natural Resources", "TSX:CNQ"),
        R("AKRBP.OL", "Aker BP", "OSL:AKRBP"),
        R("VAR.OL", "Vår Energi", "OSL:VAR"),
        R("HBR.L", "Harbour Energy", "LSE:HBR"),
        R("TOU.TO", "Tourmaline Oil", "TSX:TOU"),
        R("XLE", "Energy Select Sector SPDR", "AMEX:XLE", "etf"),
        R("XOP", "SPDR S&P Oil & Gas E&P", "AMEX:XOP", "etf"),
    ])]),
    dict(id="lundin", label="Lundin Group", sections=[dict(label=None, rows=[
        R("ORRON.ST", "Orrön Energy", "OMXSTO:ORRON"),
        R("IPCO.TO", "International Petroleum Corp", "TSX:IPCO"),
        R("LUN.TO", "Lundin Mining", "TSX:LUN"),
        R("LUG.TO", "Lundin Gold", "TSX:LUG"),
        R("NGEX.TO", "NGEx Minerals", "TSX:NGEX", note="Valle Ancho spin-out (Valiente Resources) pending Q4 2026: expect a price discontinuity."),
        R("LUC.TO", "Lucara Diamond", "TSX:LUC"),
        R("MAU.TO", "Montage Gold", "TSX:MAU"),
        R("LUNR.TO", "LunR Royalties", "TSX:LUNR", note="Listed ~Jan 2026: short history. Not the Nasdaq 'LUNR' (Intuitive Machines)."),
        R("SNM.OL", "ShaMaran Petroleum", "OSL:SNM", note="Euronext Growth Oslo since Jun 2026: short Yahoo history."),
    ])]),
    dict(id="metals", label="Metals & Mining", sections=[dict(label=None, rows=[
        R("BHP.L", "BHP", "LSE:BHP"),
        R("RIO.L", "Rio Tinto", "LSE:RIO"),
        R("GLEN.L", "Glencore", "LSE:GLEN"),
        R("AAL.L", "Anglo American", "LSE:AAL"),
        R("ANTO.L", "Antofagasta", "LSE:ANTO"),
        R("FCX", "Freeport-McMoRan", "NYSE:FCX"),
        R("FM.TO", "First Quantum", "TSX:FM"),
        R("TECK-B.TO", "Teck Resources B", "TSX:TECK.B"),
        R("LUN.TO", "Lundin Mining", "TSX:LUN"),
        R("BOL.ST", "Boliden", "OMXSTO:BOL"),
        R("NHY.OL", "Norsk Hydro", "OSL:NHY"),
        R("NEM", "Newmont", "NYSE:NEM"),
        R("B", "Barrick Mining", "NYSE:B"),
        R("AEM", "Agnico Eagle", "NYSE:AEM"),
        R("LUG.TO", "Lundin Gold", "TSX:LUG"),
        R("CCJ", "Cameco", "NYSE:CCJ"),
        R("GDX", "VanEck Gold Miners", "AMEX:GDX", "etf"),
        R("COPX", "Global X Copper Miners", "AMEX:COPX", "etf"),
    ])]),
    dict(id="commodities", label="Commodities", sections=[dict(label=None, rows=[
        R("BZ=F", "Brent crude", "OANDA:BCOUSD", "future"),
        R("CL=F", "WTI crude", "OANDA:WTICOUSD", "future"),
        R("NG=F", "Henry Hub gas", "OANDA:NATGASUSD", "future"),
        R("TTF=F", "Dutch TTF gas", "ICEEUR:TFM1!", "future", note="Yahoo TTF=F: sparse metadata/volume."),
        R("GC=F", "Gold", "OANDA:XAUUSD", "future"),
        R("SI=F", "Silver", "OANDA:XAGUSD", "future"),
        R("HG=F", "Copper (COMEX)", "OANDA:XCUUSD", "future"),
        R("PL=F", "Platinum", "OANDA:XPTUSD", "future"),
        R("U-UN.TO", "Sprott Physical Uranium", "TSX:U.UN", "etf"),
        R("CO2.L", "EU carbon (EUA ETC)", "LSE:CO2", "etf", note="SparkChange physical EUA ETC: thin volume."),
    ])]),
    dict(id="indices", label="Indices", sections=[dict(label=None, rows=[
        R("^GSPC", "S&P 500", "OANDA:SPX500USD", "index"),
        R("^IXIC", "Nasdaq Composite", "NASDAQ:IXIC", "index"),
        R("^DJI", "Dow Jones", "OANDA:US30USD", "index"),
        R("^STOXX", "STOXX Europe 600", "TVC:SXXP", "index"),
        R("^STOXX50E", "Euro Stoxx 50", "OANDA:EU50EUR", "index"),
        R("^GDAXI", "DAX", "OANDA:DE30EUR", "index"),
        R("^FTSE", "FTSE 100", "OANDA:UK100GBP", "index"),
        R("^SSMI", "SMI", "OANDA:CH20CHF", "index"),
        R("OSEBX.OL", "Oslo Børs Benchmark", "OSL:OSEBX", "index"),
        R("^OMX", "OMX Stockholm 30", "OMXSTO:OMXS30", "index"),
        R("^OMXC25", "OMX Copenhagen 25", "OMXCOP:OMXC25", "index"),
        R("^OMXH25", "OMX Helsinki 25", "OMXHEX:OMXH25", "index"),
        R("^N225", "Nikkei 225", "OANDA:JP225USD", "index"),
        R("^HSI", "Hang Seng", "OANDA:HK33HKD", "index"),
        R("^VIX", "CBOE VIX", "TVC:VIX", "index"),
    ])]),
    dict(id="rates", label="Rates & FX", sections=[
        dict(label="US Treasury yields (%)", rows=[
            R("^IRX", "US 13-week T-bill", "TVC:US03MY", "yield"),
            R("^FVX", "US 5Y yield", "TVC:US05Y", "yield"),
            R("^TNX", "US 10Y yield", "TVC:US10Y", "yield"),
            R("^TYX", "US 30Y yield", "TVC:US30Y", "yield"),
            R("TLT", "iShares 20+Y Treasury (TLT)", "NASDAQ:TLT", "etf"),
        ]),
        dict(label="FX", rows=[
            R("DX-Y.NYB", "US Dollar Index", "TVC:DXY", "fx"),
            R("CHF=X", "USD/CHF", "OANDA:USDCHF", "fx"),
            R("EURCHF=X", "EUR/CHF", "OANDA:EURCHF", "fx"),
            R("GBPCHF=X", "GBP/CHF", "OANDA:GBPCHF", "fx"),
            R("EURUSD=X", "EUR/USD", "OANDA:EURUSD", "fx"),
            R("JPY=X", "USD/JPY", "OANDA:USDJPY", "fx"),
            R("EURNOK=X", "EUR/NOK", "OANDA:EURNOK", "fx"),
            R("EURSEK=X", "EUR/SEK", "OANDA:EURSEK", "fx"),
        ]),
    ]),
]
